<?php
/**
 * Created by PhpStorm.
 * User: romai
 * Date: 23.07.2021
 * Time: 17:11
 */
namespace app\modules\account\controllers;

use yii\web\Controller;
use yii\filters\AccessControl;
use app\modules\account\models\Category;
use app\modules\account\models\Information;

class AppAccountController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                //'actions' => ['send-email', 'reset-password'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['login', 'signup', 'send-email', 'reset-password'],
                        'roles' => ['?'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public $categories;
    public $information;
    public function beforeAction($action)
    {
        $categories = Category::find()->all();
        $information = Information::findOne(1);

        $this->information = $information;
        $this->categories = $categories;


        $this->view->title = \Yii::$app->name;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

}